#!/usr/bin/python
import sys, subprocess

verbose = False
start_idx = 1
if len(sys.argv) > 1:
  if sys.argv[1] == '-v':
    verbose = True
    start_idx += 1


def trans():
  return subprocess.check_output(sys.argv[start_idx:], stdin=open('/dev/clipboard', 'r'))

new = trans()
if verbose:
  sys.stdout.write(new)
open('/dev/clipboard', 'w').write(new)

