#!/usr/bin/env python

import sys


linesize = 60

if len(sys.argv) > 1:
  if sys.argv[1].startswith('-'):
    linesize = int(sys.argv[1][1:])

def w(c):
  sys.stdout.write(c)

cnt = 0
linebreak = True
while True:
  c = sys.stdin.read(1)

  # print repr(c)

  if c == '':
    break
  elif c in " \r\n\t":
    if not linebreak:
      linebreak = True
      w(" ")
    else:
      linebreak = False
      continue

    if cnt > linesize:
      w("\n")
      cnt = 0
  else:
    w(c)
    cnt = cnt + 1

  
